pipeline {
    //agent any
    agent {
        docker 'node:latest' }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'npm run build'
                sh 'kill $(cat .pidfile)'
                sh 'npm start & sleep 1 & echo $! > .pidfile'
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}